def init() -> None: ...
def trace(message: str) -> None: ...
def debug(message: str) -> None: ...
def info(message: str) -> None: ...
def warn(message: str) -> None: ...
def error(message: str) -> None: ...

class Level:
    TRACE: Level
    DEBUG: Level
    INFO: Level
    WARN: Level
    ERROR: Level
