from string.templatelib import Template
from typing import Any

def init() -> None: ...
def trace(message: Template | str | Any | None = None, **kwargs) -> None: ...
def debug(message: Template | str | Any | None = None, **kwargs) -> None: ...
def info(message: Template | str | Any | None = None, **kwargs) -> None: ...
def warn(message: Template | str | Any | None = None, **kwargs) -> None: ...
def error(message: Template | str | Any | None = None, **kwargs) -> None: ...

class Level:
    TRACE: Level
    DEBUG: Level
    INFO: Level
    WARN: Level
    ERROR: Level
