def init() -> None: ...
def trace(message: str) -> None: ...
def debug(message: str) -> None: ...
def info(message: str) -> None: ...
def warn(message: str) -> None: ...
def error(message: str) -> None: ...
